---
dist: bionic
language: python
python:
- 3.6
env:
  global:
  - VAGRANT_VER: 2.2.9
  matrix:
  - MOLECULE_DISTRO_BOX: enr0s/ubuntu-focal
install:
- sudo add-apt-repository universe && sudo apt update
- wget https://releases.hashicorp.com/vagrant/$VAGRANT_VER/vagrant_"$VAGRANT_VER"_x86_64.deb
- sudo dpkg -i vagrant_"$VAGRANT_VER"_x86_64.deb
- sudo apt install qemu-kvm qemu-utils libvirt-bin libvirt0 libvirt-dev sshpass
- vagrant plugin install vagrant-libvirt
- pip install molecule=='3.0.6' molecule-vagrant docker python-vagrant paramiko ansible-lint yamllint travis-wait-improved
- sudo chmod o+rwx /var/run/libvirt/libvirt-sock
script:
- ansible --version
- molecule --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
- travis-wait-improved --timeout 30m molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
